services:
  - type: web
    name: readmission-risk-api
    env: python
    workingDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
